name: Check Geyser Updates

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  issues: write  # Allows issue creation

jobs:
  check-geyser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Get current Geyser version
        id: current_geyser
        run: |
          if [ -f "GEYSER_VERSION" ]; then
            CURRENT_VERSION=$(cat GEYSER_VERSION)
          else
            CURRENT_VERSION="none"
          fi
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Fetch latest Geyser version from API
        id: fetch_latest
        run: |
          # Fetch the latest version JSON
          LATEST_JSON=$(curl -s "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest")
          echo "Raw JSON Response: $LATEST_JSON"  # Debugging output
          
          # Ensure jq is installed
          if ! command -v jq &> /dev/null; then
            echo "jq command not found. Installing..."
            sudo apt update && sudo apt install -y jq
          fi

          # Extract the latest build number
          LATEST_BUILD=$(echo "$LATEST_JSON" | jq -r '.build // empty')

          if [ -z "$LATEST_BUILD" ]; then
            echo "Error: Failed to extract the latest build number!"
            exit 1
          fi

          echo "latest_build=$LATEST_BUILD" >> $GITHUB_OUTPUT

      - name: Compare versions and create GitHub Issue if new
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT=${{ steps.current_geyser.outputs.current_version }}
          LATEST=${{ steps.fetch_latest.outputs.latest_build }}

          echo "Current build: $CURRENT"
          echo "Latest build:  $LATEST"

          if [ "$CURRENT" = "$LATEST" ]; then
            echo "Already up to date."
          else
            echo "New Geyser build found ($LATEST), creating an issue..."

            # Extract repository owner and name
            REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
            REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

            # Create a GitHub issue
            gh api repos/$REPO_OWNER/$REPO_NAME/issues \
              -f title="New Geyser version: build $LATEST" \
              -f body="We have Geyser build $CURRENT, latest is $LATEST. Please update." \
              --method POST || echo "Failed to create issue."
