name: Deploy Minecraft Server with rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 193.203.167.72 >> ~/.ssh/known_hosts

      - name: Ensure Remote Directory Exists
        run: |
          ssh root@193.203.167.72 "mkdir -p /home/minecraft/minecraft_server && chown -R minecraft:minecraft /home/minecraft"

      - name: Convert .gitignore to rsync exclude file
        run: |
          grep -v '^#' .gitignore | grep -v '^$' | sed 's:^/:**/:' > .rsync-exclude

      - name: Deploy Files Using rsync (Upload Only, No Deletes)
        run: |
          rsync -avzu --exclude-from=.rsync-exclude -e "ssh -i ~/.ssh/id_rsa" ./ root@193.203.167.72:/home/minecraft/minecraft_server/

      - name: Set execute permissions on scripts
        run: |
          ssh -T root@193.203.167.72 << 'EOF'
            chmod +x /home/minecraft/minecraft_server/scripts/*
          EOF

      - name: Update Geyser Plugin on remote server
        run: |
          ssh -T root@193.203.167.72 << EOF
            # Download the latest Geyser plugin
            curl -L -o /home/minecraft/minecraft_server/plugins/Geyser-Spigot.jar \
              "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"

            # Fix permissions so the minecraft user owns it
            chown minecraft:minecraft /home/minecraft/minecraft_server/plugins/Geyser-Spigot.jar

            echo "Geyser plugin has been updated."
          EOF

      - name: Install Java and Run Minecraft Server with Screen
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          ssh -T root@193.203.167.72 << EOF
            # Install Java JDK 21 if not already installed
            if ! java -version 2>&1 | grep -q 'openjdk 21'; then
              echo "Java 21 not found. Installing..."
              apt update && apt install -y openjdk-21-jdk
            else
              echo "Java 21 is already installed."
            fi

            # Install screen if not already installed
            if ! command -v screen &> /dev/null; then
              echo "screen not found. Installing..."
              apt install -y screen
            else
              echo "screen is already installed."
            fi

            # Create user and directories if not present
            useradd -m -s /bin/bash minecraft || true
            mkdir -p /home/minecraft/minecraft_server
            chown -R minecraft:minecraft /home/minecraft

            # If worlds.zip is missing but worlds_static.zip exists, copy it over
            if [ ! -f /home/root/minecraft_data/worlds.zip ] && [ -f /home/root/minecraft_data/worlds_static.zip ]; then
              cp /home/root/minecraft_data/worlds_static.zip /home/root/minecraft_data/worlds.zip
              echo "No worlds.zip found. Copied worlds_static.zip to worlds.zip"
            fi

            # Unzip worlds.zip if the world directory does not exist
            if [ ! -d /home/minecraft/minecraft_server/world ]; then
              if [ -f /home/root/minecraft_data/worlds.zip ]; then
                echo "Found worlds.zip in /home/root/minecraft_data, proceeding to unzip..."
                unzip -n /home/root/minecraft_data/worlds.zip -d /home/minecraft/minecraft_server/
                chown -R minecraft:minecraft /home/minecraft/minecraft_server/
              else
                echo "worlds.zip not found in /home/root/minecraft_data!"
              fi
            else
              echo "World directory already exists. Skipping unzip."
            fi

            # Overwrite the DiscordSRV BotToken
            echo "Setting DiscordSRV BotToken from GitHub secret..."
            sed -i "s@^BotToken:.*@BotToken: \"${DISCORD_BOT_TOKEN}\"@" /home/minecraft/minecraft_server/plugins/DiscordSRV/config.yml || true

            # Overwrite the 'Channels: { "global": ... }' line with the production channel ID
            echo "Setting Channels property to production..."
            sed -i 's@Channels: { "global": ".*" }@Channels: { "global": "1077792065955577886" }@' /home/minecraft/minecraft_server/plugins/DiscordSRV/config.yml || true

            # Stop any existing screen session
            echo "Attempting to stop existing Minecraft server..."
            screen -S minecraft_server -X stuff "stop^M" || true
            sleep 5
            screen -S minecraft_server -X quit || true

            # Start the Minecraft server in a screen session
            cd /home/minecraft/minecraft_server
            screen -dmS minecraft_server bash -c 'java -Xmx12G -Xms4G -jar purpur.jar nogui'

            echo "Minecraft server started in a screen session named 'minecraft_server'."
          EOF

      - name: Wait for server to finish loading
        run: |
          ssh -T root@193.203.167.72 << EOF
            echo "Waiting for 'Done' message in the log..."
            tail -n 0 -F /home/minecraft/minecraft_server/logs/latest.log | grep -m1 "Done"
            echo "Minecraft server startup complete!"
          EOF
