name: FTP Deploy

on:
  push:
    branches:
      - main  # Change if you want to deploy from a different branch

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./  # Specify the directory to upload (e.g., ./ for entire repo or ./dist for build files)
          server-dir: /  # Adjust the target directory on your FTP server
          dangerous-clean-slate: false  # Set to true if you want to wipe the server before upload
