name: Deploy Minecraft Server with rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 193.203.167.72 >> ~/.ssh/known_hosts

      - name: Ensure Remote Directory Exists
        run: |
          ssh root@193.203.167.72 "mkdir -p /home/minecraft/minecraft_server && chown -R minecraft:minecraft /home/minecraft"

      - name: Deploy Files Using rsync (Avoid Deleting Worlds)
        run: |
          # Exclude persistent directories and the worlds.zip from deletion.
          rsync -avz --delete \
            --exclude='bluemap' \
            --exclude='world' \
            --exclude='world_nether' \
            --exclude='lobby' \
            --exclude='home/root/minecraft_data/worlds.zip' \
            -e "ssh -i ~/.ssh/id_rsa" ./ root@193.203.167.72:/home/minecraft/minecraft_server/

      - name: Build and Run Docker on VPS
        run: |
          ssh -T root@193.203.167.72 << 'EOF'
            # Create necessary directories and user if not already present
            useradd -m -s /bin/bash minecraft || true
            mkdir -p /home/minecraft/minecraft_server
            chown -R minecraft:minecraft /home/minecraft

            # If worlds.zip is missing but worlds_static.zip exists, copy worlds_static.zip to worlds.zip
            if [ ! -f /home/root/minecraft_data/worlds.zip ] && [ -f /home/root/minecraft_data/worlds_static.zip ]; then
              cp /home/root/minecraft_data/worlds_static.zip /home/root/minecraft_data/worlds.zip
              echo "No worlds.zip found. Copied worlds_static.zip to worlds.zip"
            fi

            # Unzip worlds.zip from root path if the world directory does not exist
            if [ ! -d /home/minecraft/minecraft_server/world ]; then
              if [ -f /home/root/minecraft_data/worlds.zip ]; then
                echo "Found worlds.zip in /home/root/minecraft_data, proceeding to unzip..."
                unzip -n /home/root/minecraft_data/worlds.zip -d /home/minecraft/minecraft_server/
                chown -R minecraft:minecraft /home/minecraft/minecraft_server/
              else
                echo "worlds.zip not found in /home/root/minecraft_data!"
              fi
            else
              echo "World directory already exists. Skipping unzip."
            fi

            # Build and run the Docker container
            cd /home/minecraft/minecraft_server
            if [ -f Dockerfile ]; then
              docker build -t minecraft-server .
            else
              echo "No Dockerfile found in /home/minecraft/minecraft_server. Aborting."
              exit 1
            fi

            # Stop and remove the existing container if it exists
            docker stop minecraft_server || true
            docker rm minecraft_server || true

            # Run the Docker container with world and BlueMap data mounted
            docker run -d \
              -p 25565:25565 \
              -p 8100:8100 \
              -p 19132:19132/udp \
              -v /home/minecraft/minecraft_server/world:/home/minecraft/minecraft_server/world \
              -v /home/minecraft/minecraft_server/world_nether:/home/minecraft/minecraft_server/world_nether \
              -v /home/minecraft/minecraft_server/lobby:/home/minecraft/minecraft_server/lobby \
              -v /home/minecraft/minecraft_server/plugins/BlueMap:/home/minecraft/minecraft_server/plugins/BlueMap \
              --user minecraft \
              --name minecraft_server \
              minecraft-server
          EOF
