name: Deploy Minecraft Server without Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 193.203.167.72 >> ~/.ssh/known_hosts

      - name: Ensure Remote Directories
        run: |
          ssh root@193.203.167.72 "
            mkdir -p /home/minecraft/minecraft_server
            chown -R minecraft:minecraft /home/minecraft
          "

      - name: Deploy Files Using rsync
        run: |
          # Exclude any dynamic/persistent data you don't want overwritten
          rsync -avz --delete \
            --exclude='bluemap' \
            --exclude='world' \
            --exclude='world_nether' \
            --exclude='lobby' \
            --exclude='db/' \
            --exclude='data/' \
            --exclude='plugins/**/data/' \
            -e "ssh -i ~/.ssh/id_rsa" ./ root@193.203.167.72:/home/minecraft/minecraft_server/

      - name: Run Minecraft Server with screen
        run: |
          ssh -T root@193.203.167.72 << 'EOF'
            # 1. Install Java 21 and screen if not installed
            if ! java -version 2>&1 | grep -q 'openjdk 21'; then
              echo "Installing Java 21..."
              apt update && apt install -y openjdk-21-jdk
            else
              echo "Java 21 is already installed."
            fi

            if ! command -v screen &> /dev/null; then
              echo "Installing screen..."
              apt install -y screen
            else
              echo "screen is already installed."
            fi

            # 2. Stop any existing server session
            echo "Attempting to stop existing Minecraft server..."
            # Send 'stop' command to the screen session (if it exists)
            screen -S minecraft_server -X stuff "stop^M" || true
            # Give it a few seconds to stop gracefully
            sleep 5
            # Force quit the screen session if still active
            screen -S minecraft_server -X quit || true

            # 3. Start the server in a new screen session
            cd /home/minecraft/minecraft_server
            echo "Starting new Minecraft server screen session..."
            screen -dmS minecraft_server java -Xmx12G -Xms4G -jar purpur.jar nogui
          EOF
