name: Deploy Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 82.180.136.100
          username: minecraft
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          debug: true
          script: |
            cd /home/minecraft/minecraft-server
            git pull origin main
            screen -S minecraft -X quit
            screen -dmS minecraft java -Xmx14G -Xms14G -jar purpur.jar nogui
